package country;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientDetailsProto.proto

public final class ClientDetailsProto {
  private ClientDetailsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string category = 2;</code>
     */
    boolean hasCategory();
    /**
     * <code>required string category = 2;</code>
     */
    java.lang.String getCategory();
    /**
     * <code>required string category = 2;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>required string description = 3;</code>
     */
    boolean hasDescription();
    /**
     * <code>required string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>required string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>required string email = 4;</code>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 4;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>required string refemail = 5;</code>
     */
    boolean hasRefemail();
    /**
     * <code>required string refemail = 5;</code>
     */
    java.lang.String getRefemail();
    /**
     * <code>required string refemail = 5;</code>
     */
    com.google.protobuf.ByteString
        getRefemailBytes();

    /**
     * <code>required string createdby = 6;</code>
     */
    boolean hasCreatedby();
    /**
     * <code>required string createdby = 6;</code>
     */
    java.lang.String getCreatedby();
    /**
     * <code>required string createdby = 6;</code>
     */
    com.google.protobuf.ByteString
        getCreatedbyBytes();

    /**
     * <code>required string password = 7;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 7;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 7;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>required int64 phonenum = 8;</code>
     */
    boolean hasPhonenum();
    /**
     * <code>required int64 phonenum = 8;</code>
     */
    long getPhonenum();

    /**
     * <code>repeated string apikey = 9;</code>
     */
    com.google.protobuf.ProtocolStringList
        getApikeyList();
    /**
     * <code>repeated string apikey = 9;</code>
     */
    int getApikeyCount();
    /**
     * <code>repeated string apikey = 9;</code>
     */
    java.lang.String getApikey(int index);
    /**
     * <code>repeated string apikey = 9;</code>
     */
    com.google.protobuf.ByteString
        getApikeyBytes(int index);
  }
  /**
   * Protobuf type {@code ClientDetails}
   */
  public static final class ClientDetails extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientDetails)
      ClientDetailsOrBuilder {
    // Use ClientDetails.newBuilder() to construct.
    private ClientDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientDetails(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientDetails defaultInstance;
    public static ClientDetails getDefaultInstance() {
      return defaultInstance;
    }

    public ClientDetails getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              category_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              description_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              email_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              refemail_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              createdby_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              password_ = bs;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              phonenum_ = input.readInt64();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                apikey_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000100;
              }
              apikey_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          apikey_ = apikey_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientDetailsProto.internal_static_ClientDetails_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientDetailsProto.internal_static_ClientDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientDetailsProto.ClientDetails.class, ClientDetailsProto.ClientDetails.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientDetails> PARSER =
        new com.google.protobuf.AbstractParser<ClientDetails>() {
      public ClientDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientDetails(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientDetails> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORY_FIELD_NUMBER = 2;
    private java.lang.Object category_;
    /**
     * <code>required string category = 2;</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string category = 2;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          category_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string category = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    /**
     * <code>required string description = 3;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private java.lang.Object email_;
    /**
     * <code>required string email = 4;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string email = 4;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFEMAIL_FIELD_NUMBER = 5;
    private java.lang.Object refemail_;
    /**
     * <code>required string refemail = 5;</code>
     */
    public boolean hasRefemail() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string refemail = 5;</code>
     */
    public java.lang.String getRefemail() {
      java.lang.Object ref = refemail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          refemail_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string refemail = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRefemailBytes() {
      java.lang.Object ref = refemail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refemail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEDBY_FIELD_NUMBER = 6;
    private java.lang.Object createdby_;
    /**
     * <code>required string createdby = 6;</code>
     */
    public boolean hasCreatedby() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string createdby = 6;</code>
     */
    public java.lang.String getCreatedby() {
      java.lang.Object ref = createdby_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          createdby_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string createdby = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedbyBytes() {
      java.lang.Object ref = createdby_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdby_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 7;
    private java.lang.Object password_;
    /**
     * <code>required string password = 7;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string password = 7;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONENUM_FIELD_NUMBER = 8;
    private long phonenum_;
    /**
     * <code>required int64 phonenum = 8;</code>
     */
    public boolean hasPhonenum() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int64 phonenum = 8;</code>
     */
    public long getPhonenum() {
      return phonenum_;
    }

    public static final int APIKEY_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList apikey_;
    /**
     * <code>repeated string apikey = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getApikeyList() {
      return apikey_;
    }
    /**
     * <code>repeated string apikey = 9;</code>
     */
    public int getApikeyCount() {
      return apikey_.size();
    }
    /**
     * <code>repeated string apikey = 9;</code>
     */
    public java.lang.String getApikey(int index) {
      return apikey_.get(index);
    }
    /**
     * <code>repeated string apikey = 9;</code>
     */
    public com.google.protobuf.ByteString
        getApikeyBytes(int index) {
      return apikey_.getByteString(index);
    }

    private void initFields() {
      name_ = "";
      category_ = "";
      description_ = "";
      email_ = "";
      refemail_ = "";
      createdby_ = "";
      password_ = "";
      phonenum_ = 0L;
      apikey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCategory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRefemail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreatedby()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhonenum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCategoryBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getEmailBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getRefemailBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getCreatedbyBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, phonenum_);
      }
      for (int i = 0; i < apikey_.size(); i++) {
        output.writeBytes(9, apikey_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCategoryBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getEmailBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getRefemailBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getCreatedbyBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, phonenum_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < apikey_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(apikey_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getApikeyList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ClientDetailsProto.ClientDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientDetailsProto.ClientDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientDetailsProto.ClientDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientDetailsProto.ClientDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientDetailsProto.ClientDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientDetailsProto.ClientDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ClientDetailsProto.ClientDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ClientDetailsProto.ClientDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ClientDetailsProto.ClientDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientDetailsProto.ClientDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ClientDetailsProto.ClientDetails prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientDetails)
        ClientDetailsProto.ClientDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientDetailsProto.internal_static_ClientDetails_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientDetailsProto.internal_static_ClientDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientDetailsProto.ClientDetails.class, ClientDetailsProto.ClientDetails.Builder.class);
      }

      // Construct using ClientDetailsProto.ClientDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        category_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        refemail_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        createdby_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        phonenum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        apikey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientDetailsProto.internal_static_ClientDetails_descriptor;
      }

      public ClientDetailsProto.ClientDetails getDefaultInstanceForType() {
        return ClientDetailsProto.ClientDetails.getDefaultInstance();
      }

      public ClientDetailsProto.ClientDetails build() {
        ClientDetailsProto.ClientDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientDetailsProto.ClientDetails buildPartial() {
        ClientDetailsProto.ClientDetails result = new ClientDetailsProto.ClientDetails(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.category_ = category_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.refemail_ = refemail_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.createdby_ = createdby_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.phonenum_ = phonenum_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          apikey_ = apikey_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.apikey_ = apikey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientDetailsProto.ClientDetails) {
          return mergeFrom((ClientDetailsProto.ClientDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientDetailsProto.ClientDetails other) {
        if (other == ClientDetailsProto.ClientDetails.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCategory()) {
          bitField0_ |= 0x00000002;
          category_ = other.category_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000004;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000008;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasRefemail()) {
          bitField0_ |= 0x00000010;
          refemail_ = other.refemail_;
          onChanged();
        }
        if (other.hasCreatedby()) {
          bitField0_ |= 0x00000020;
          createdby_ = other.createdby_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000040;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasPhonenum()) {
          setPhonenum(other.getPhonenum());
        }
        if (!other.apikey_.isEmpty()) {
          if (apikey_.isEmpty()) {
            apikey_ = other.apikey_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureApikeyIsMutable();
            apikey_.addAll(other.apikey_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasCategory()) {
          
          return false;
        }
        if (!hasDescription()) {
          
          return false;
        }
        if (!hasEmail()) {
          
          return false;
        }
        if (!hasRefemail()) {
          
          return false;
        }
        if (!hasCreatedby()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        if (!hasPhonenum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientDetailsProto.ClientDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        	
          parsedMessage = (ClientDetailsProto.ClientDetails) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <code>required string category = 2;</code>
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string category = 2;</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            category_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string category = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string category = 2;</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string category = 2;</code>
       */
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000002);
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>required string category = 2;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        category_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>required string description = 3;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 4;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string email = 4;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 4;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 4;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000008);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 4;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object refemail_ = "";
      /**
       * <code>required string refemail = 5;</code>
       */
      public boolean hasRefemail() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string refemail = 5;</code>
       */
      public java.lang.String getRefemail() {
        java.lang.Object ref = refemail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            refemail_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string refemail = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRefemailBytes() {
        java.lang.Object ref = refemail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          refemail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string refemail = 5;</code>
       */
      public Builder setRefemail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        refemail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string refemail = 5;</code>
       */
      public Builder clearRefemail() {
        bitField0_ = (bitField0_ & ~0x00000010);
        refemail_ = getDefaultInstance().getRefemail();
        onChanged();
        return this;
      }
      /**
       * <code>required string refemail = 5;</code>
       */
      public Builder setRefemailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        refemail_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object createdby_ = "";
      /**
       * <code>required string createdby = 6;</code>
       */
      public boolean hasCreatedby() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string createdby = 6;</code>
       */
      public java.lang.String getCreatedby() {
        java.lang.Object ref = createdby_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            createdby_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string createdby = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCreatedbyBytes() {
        java.lang.Object ref = createdby_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createdby_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string createdby = 6;</code>
       */
      public Builder setCreatedby(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        createdby_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string createdby = 6;</code>
       */
      public Builder clearCreatedby() {
        bitField0_ = (bitField0_ & ~0x00000020);
        createdby_ = getDefaultInstance().getCreatedby();
        onChanged();
        return this;
      }
      /**
       * <code>required string createdby = 6;</code>
       */
      public Builder setCreatedbyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        createdby_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 7;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string password = 7;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 7;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 7;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000040);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 7;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        password_ = value;
        onChanged();
        return this;
      }

      private long phonenum_ ;
      /**
       * <code>required int64 phonenum = 8;</code>
       */
      public boolean hasPhonenum() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int64 phonenum = 8;</code>
       */
      public long getPhonenum() {
        return phonenum_;
      }
      /**
       * <code>required int64 phonenum = 8;</code>
       */
      public Builder setPhonenum(long value) {
        bitField0_ |= 0x00000080;
        phonenum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 phonenum = 8;</code>
       */
      public Builder clearPhonenum() {
        bitField0_ = (bitField0_ & ~0x00000080);
        phonenum_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList apikey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureApikeyIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          apikey_ = new com.google.protobuf.LazyStringArrayList(apikey_);
          bitField0_ |= 0x00000100;
         }
      }
      /**
       * <code>repeated string apikey = 9;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getApikeyList() {
        return apikey_.getUnmodifiableView();
      }
      /**
       * <code>repeated string apikey = 9;</code>
       */
      public int getApikeyCount() {
        return apikey_.size();
      }
      /**
       * <code>repeated string apikey = 9;</code>
       */
      public java.lang.String getApikey(int index) {
        return apikey_.get(index);
      }
      /**
       * <code>repeated string apikey = 9;</code>
       */
      public com.google.protobuf.ByteString
          getApikeyBytes(int index) {
        return apikey_.getByteString(index);
      }
      /**
       * <code>repeated string apikey = 9;</code>
       */
      public Builder setApikey(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureApikeyIsMutable();
        apikey_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string apikey = 9;</code>
       */
      public Builder addApikey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureApikeyIsMutable();
        apikey_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string apikey = 9;</code>
       */
      public Builder addAllApikey(
          java.lang.Iterable<java.lang.String> values) {
        ensureApikeyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, apikey_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string apikey = 9;</code>
       */
      public Builder clearApikey() {
        apikey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string apikey = 9;</code>
       */
      public Builder addApikeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureApikeyIsMutable();
        apikey_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClientDetails)
    }

    static {
      defaultInstance = new ClientDetails(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClientDetails)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientDetails_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ClientDetailsProto.proto\"\254\001\n\rClientDet" +
      "ails\022\014\n\004name\030\001 \002(\t\022\020\n\010category\030\002 \002(\t\022\023\n\013" +
      "description\030\003 \002(\t\022\r\n\005email\030\004 \002(\t\022\020\n\010refe" +
      "mail\030\005 \002(\t\022\021\n\tcreatedby\030\006 \002(\t\022\020\n\010passwor" +
      "d\030\007 \002(\t\022\020\n\010phonenum\030\010 \002(\003\022\016\n\006apikey\030\t \003(" +
      "\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ClientDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientDetails_descriptor,
        new java.lang.String[] { "Name", "Category", "Description", "Email", "Refemail", "Createdby", "Password", "Phonenum", "Apikey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}